plugins {
    id "com.android.application"
}

android {
    namespace "com.jianglab.babywife"
    compileSdk 35

    defaultConfig {
        applicationId "com.jianglab.babywife"
        minSdk 23
        targetSdk 35
        versionCode 2026072601
        versionName "2026.07.26.local"
    }

    flavorDimensions "brand"
    productFlavors {
        babywifeclassic {
            dimension "brand"
            versionNameSuffix "-babywife-classic"
        }
        lidacaizhu {
            dimension "brand"
            applicationIdSuffix ".lidacaizhu"
            versionNameSuffix "-lidacaizhu"
        }
        jianglab {
            dimension "brand"
            applicationIdSuffix ".jianglab"
            versionNameSuffix "-jianglab"
        }
        niubi {
            dimension "brand"
            applicationIdSuffix ".niubi"
            versionNameSuffix "-niubi"
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging false
        }
    }
}

dependencies {
    implementation files('libs/musicbridge.aar')
}
