plugins {
    id "com.android.application"
}

android {
    namespace "com.jianglab.babywife"
    compileSdk 35
    buildToolsVersion "37.0.0"

    defaultConfig {
        applicationId "com.jianglab.babywife"
        minSdk 23
        targetSdk 35
        versionCode 2026080101
        versionName "2026.08.01.playlist-cache-skip-failed"
        buildConfigField "boolean", "REQUIRE_FIRST_RUN_PASSPHRASE", "false"
    }

    buildFeatures {
        buildConfig true
    }

    flavorDimensions "brand"
    productFlavors {
        babywifeclassic {
            dimension "brand"
            versionNameSuffix "-babywife-classic"
        }
        lidacaizhu {
            dimension "brand"
            applicationIdSuffix ".lidacaizhu"
            versionNameSuffix "-lidacaizhu"
        }
        jianglab {
            dimension "brand"
            applicationIdSuffix ".jianglab"
            versionNameSuffix "-jianglab"
            buildConfigField "boolean", "REQUIRE_FIRST_RUN_PASSPHRASE", "true"
        }
        niubi {
            dimension "brand"
            applicationIdSuffix ".niubi"
            versionNameSuffix "-niubi"
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging false
        }
    }
}

dependencies {
    implementation files('libs/musicbridge.aar')
}
